apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 10m
  chart:
    spec:
      chart: sonarqube
      version: 10.5.0+500
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
      interval: 10m
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      size: 10Gi
    postgresql:
      enabled: true


