apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m
  chart:
    spec:
      chart: velero
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 10m
  values:
    configuration:
      provider: aws
      backupStorageLocation:
        bucket: velero-backups
        config:
          region: us-west-2
      volumeSnapshotLocation:
        config:
          region: us-west-2
    credentials:
      useSecret: false
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.8.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    serviceAccount:
      server:
        create: true
        annotations: {}
    rbac:
      create: true
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
