apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: heimdall
  namespace: heimdall
spec:
  interval: 10m
  chart:
    spec:
      chart: heimdall
      version: 10.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  values:
    service:
      type: ClusterIP


